### ISSUE TITLE
SSL test throws Exception when run ITTLSTest

### ISSUE THREAD

**Issue by chilly** [nats-io/java-nats#104]
[TEST START] testTlsSuccessSecureConnect
[TEST ENDED] Time elapsed: 7.822 sec

javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at io.nats.client.TcpConnection.makeTls(TcpConnection.java:193)
	at io.nats.client.TcpConnection.makeTls(TcpConnection.java:180)
	at io.nats.client.ConnectionImpl.makeTlsConn(ConnectionImpl.java:699)
	at io.nats.client.ConnectionImpl.checkForSecure(ConnectionImpl.java:692)
	at io.nats.client.ConnectionImpl.processExpectedInfo(ConnectionImpl.java:723)
	at io.nats.client.ConnectionImpl.processConnectInit(ConnectionImpl.java:666)
	at io.nats.client.ConnectionImpl.connect(ConnectionImpl.java:411)
	at io.nats.client.ConnectionFactory.createConnection(ConnectionFactory.java:217)
	at io.nats.client.ITTLSTest.testTlsSuccessSecureConnect(ITTLSTest.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 255

and testTlsSuccessWithCert() throw exception also.

**Comment by chilly** [comment]
I use gnatsd  0.9.6 version

**Comment by mcqueary** [comment]
@chilly usually we see this occur when there is a timing issue (e.g. in Travis CI, where things can run very slowly at times). What environment are you running this in?

**Comment by chilly** [comment]
start = System.currentTimeMillis();   
System.out.println("start connection:"+start);
            try (Connection connection = cf.createConnection()) {
                assertFalse(connection.isClosed());

                connection.publish("foo", "Hello".getBytes());
                connection.close();
            } finally {
                srv.shutdown();
            }
        } catch (Exception e1) {
            System.out.println("end cost:"+(System.currentTimeMillis()-start));
            e1.printStackTrace();
            throw (e1);
        }


it cost 5 sec.  and total testcase run 7 sec. I already changed tcp connect timeout = 10 sec. 
So I think it is not time issue. I run it in Intellij.

**Comment by chilly** [comment]
Inheriting IO, psInfo =/workspace/java-nats/target/gnatsd -DV -config /workspace/java-nats/src/test/resources/tls_1222_verify.conf
Started [/workspace/java-nats/target/gnatsd -DV -config /workspace/java-nats/src/test/resources/tls_1222_verify.conf]
[7128] 2017/03/07 14:13:43.842556 [INF] Starting nats-server version 0.9.6
[7128] 2017/03/07 14:13:43.842669 [DBG] Go build version go1.7.4
[7128] 2017/03/07 14:13:43.842681 [INF] Listening for client connections on localhost:1222
[7128] 2017/03/07 14:13:43.843163 [INF] TLS required for client connections
[7128] 2017/03/07 14:13:43.843171 [DBG] Server id is fmEqfMOwZZSNEqX06MLXIp
[7128] 2017/03/07 14:13:43.843173 [INF] Server is ready
[7128] 2017/03/07 14:13:52.379840 [DBG] 127.0.0.1:58195 - cid:1 - Client connection created
[7128] 2017/03/07 14:13:52.379892 [DBG] 127.0.0.1:58195 - cid:1 - Starting TLS client connection handshake
[7128] 2017/03/07 14:13:52.880776 [DBG] 127.0.0.1:58195 - cid:1 - TLS handshake error: read tcp 127.0.0.1:1222->127.0.0.1:58195: i/o timeout
[7128] 2017/03/07 14:13:52.882625 [TRC] 127.0.0.1:58195 - cid:1 - <<- [-ERR Secure Connection - TLS Required]
[7128] 2017/03/07 14:13:52.882714 [DBG] 127.0.0.1:58195 - cid:1 - TLS handshake timeout
[7128] 2017/03/07 14:13:52.882740 [DBG] 127.0.0.1:58195 - cid:1 - Client connection closed
[7128] 2017/03/07 14:13:52.882867 [TRC] 127.0.0.1:58195 - cid:1 - <<- [-ERR Secure Connection - TLS Required]
Stopped [/workspace/java-nats/target/gnatsd -DV -config /workspace/java-nats/src/test/resources/tls_1222_verify.conf]
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

**Comment by chilly** [comment]
Why i/o timeout ? The time is less then 1 sec. How to solve this case?

**Comment by chilly** [comment]
I find the solution in gnatsd. In server.go file,  Change s.opts.TLSTimeout to 6 or much longer. The connect will be established.

**Comment by mcqueary** [comment]
Thanks for letting us know, @chilly ... I assume you mean you changed it in the config file, right?

**Comment by chilly** [comment]
O, I changed the code.  But you want to change config file.
try 

tls {
 timeout: 6
}
