### ISSUE TITLE
Support a socket read timeout in the connection properties

### ISSUE THREAD

**Issue by mpilone** [nats-io/java-nats#130]
I ran into an issue where one of the machines running a nats instance locked up in a state where it would accept TCP connections but not respond/process data. That's a separate issue unrelated to nats. However while the machine was in this state, I found that Java applications using the Java client would hang at startup if they selected this broken remote server.

From the stack trace (see below), it looks like the Java nats client is stuck on a read call that never returns. Looking through the code, it appears that a timeout used used during the socket connect call in TcpConnection around line 73, but no setSoTimeout is called on the socket after connection. My understanding is that the default read timeout of a Java socket is 0 which means it will block indefinitely.

There is a comment in TcpConnection around line 91 that seems to hit at someone thinking about adding a send/read timeout but it clearly isn't implemented:

```void setConnectTimeout(int value) {
        this.timeout = value;
    }

    // setSendTimeout?

    boolean isSetup() {
        return (client != null);
    }
```

To support the most robust fail over and startup, it seems like a socket read timeout needs to be set with either a reasonable default or configurable via options.

-mike

Stack trace:
```"WrapperSimpleAppMain" #16 prio=5 os_prio=0 tid=0x00007f8d04001000 nid=0x6191 runnable [0x00007f8d520e8000]
   java.lang.Thread.State: RUNNABLE
      at java.net.SocketInputStream.socketRead0(Native Method)
      at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
      at java.net.SocketInputStream.read(SocketInputStream.java:170)
      at java.net.SocketInputStream.read(SocketInputStream.java:141)
      at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
      at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
      at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
      - locked <0x00000000f8d77a70> (a java.io.BufferedInputStream)
      at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
      at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
      at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
      - locked <0x00000000f8d88588> (a java.io.InputStreamReader)
      at java.io.InputStreamReader.read(InputStreamReader.java:184)
      at java.io.BufferedReader.fill(BufferedReader.java:161)
      at java.io.BufferedReader.readLine(BufferedReader.java:324)
      - locked <0x00000000f8d88588> (a java.io.InputStreamReader)
      at java.io.BufferedReader.readLine(BufferedReader.java:389)
      at io.nats.client.ConnectionImpl.readLine(ConnectionImpl.java:1192)
      at io.nats.client.ConnectionImpl.readOp(ConnectionImpl.java:1256)
      at io.nats.client.ConnectionImpl.processExpectedInfo(ConnectionImpl.java:708)
      at io.nats.client.ConnectionImpl.processConnectInit(ConnectionImpl.java:665)
      at io.nats.client.ConnectionImpl.connect(ConnectionImpl.java:410)
      at io.nats.client.ConnectionFactory.createConnection(ConnectionFactory.java:217)
      at org.p.c.integration.util.camel.nats.NatsEndpoint.createConnection(NatsEndpoint.java:107)
      at org.p.c.integration.util.camel.nats.NatsEndpoint.doStart(NatsEndpoint.java:61)```

**Comment by ColinSullivan1** [comment]
@mpilone , thank you for raising the issue; this feature does look like it was considered at one time, and certainly seems like a reasonable request.  Would you be interested in submitting a PR?

Thanks,
Colin

**Comment by sasbury** [comment]
I will take a look at this for 2.0.1.

**Comment by mpilone** [comment]
I should add that I did briefly look into implementing a fix for this but I ran into an issue where it would require a fundamental rewrite of the client. I don't completely remember the details because it was a while ago but I seem to remember that the current implementation relies on input streams or socket blocking while waiting for client input that would break if a socket timeout was implemented.

If someone has the time it might be worth rewriting the client to use nio, non-blocking communication but I didn't have the time when I originally found the issue.

**Comment by sasbury** [comment]
The new client is still blocking, I did a non-blocking version with TLS but it was much more complex and wasn't giving better performance (probably because we just have one incoming connection.) I will take a look though to see if we can set a timeout and recover from it reasonably. The new library does have a fair bit of recovery built in, so maybe we aren't too far away.

**Comment by sasbury** [comment]
Closing for now, open to a PR if you have time.
