### ISSUE TITLE
An Exception on Android

### ISSUE THREAD

**Issue by xy02** [nats-io/java-nats#161]
I got an Exception on Android 4.0.3

E/AndroidRuntime: FATAL EXCEPTION: Thread-154
    java.lang.IllegalAccessError: tried to access method java.util.concurrent.ScheduledThreadPoolExecutor.setRemoveOnCancelPolicy:()Ljava/util/concurrent/ScheduledExecutorService; from class io.nats.client.ConnectionImpl
        at io.nats.client.ConnectionImpl.createScheduler(ConnectionImpl.java:235)
        at io.nats.client.ConnectionImpl.setup(ConnectionImpl.java:248)
        at io.nats.client.ConnectionImpl.connect(ConnectionImpl.java:408)
        at io.nats.client.Options.connect(Options.java:212)
        at io.nats.client.Nats.connect(Nats.java:429)
        at io.nats.client.Nats.connect(Nats.java:412)

Can anyone help?

**Comment by xy02** [comment]
I implement a NTAS client instead.
