### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by locactus** [nats-io/java-nats#169]
I keep getting out of memory errors when subscribing to a subject. I've stripped my code down to it's simplest form and ran a dispatcher putting the message onto a list in a different thread to reduce time in the Lambda function. I've noticed that the memory increases over time to hint that there is a memory leak somewhere. I've run this from out the box memory setting all the way up to 3G and still get OutOfMemoryErrors. Using version 2.0.1 

My code

`public class Dispatcher {
    private static final Logger LOGGER = LogManager.getLogger(Dispatcher.class.getName());
   
    @Value("${subscribe.subject}")
    private String subject ;
    @Autowired
    private FeedQueue feedQueue ;
   
   
    public void register(Connection connection) {
        io.nats.client.Dispatcher d = connection.createDispatcher((msg) -> {
            String response = new String(msg.getData(), StandardCharsets.UTF_8);
            //LOGGER.info(response);
            //processServiceMessageSender.send(response);
            feedQueue.add(response);
        });

        d.subscribe(subject);
        //connection.flush(null);
    }
   
}`

Error

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Nats Connection Reader"
[WARNING]
[WARNING]

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ActiveMQ InactivityMonitor ReadCheckTimer"
[WARNING]
[WARNING]
[WARNING]
java.lang.OutOfMemoryError: Java heap space
[WARNING]
java.lang.OutOfMemoryError: Java heap space

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ActiveMQ InactivityMonitor WriteCheckTimer"
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
        at io.nats.client.impl.NatsConnection$$Lambda$12/478923673.get$Lambda(Unknown Source)
        at java.lang.invoke.LambdaForm$DMH/1502168684.invokeStatic_LIL_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/1754986913.linkToTargetMethod(LambdaForm$MH)
        at io.nats.client.impl.NatsConnection.cleanResponses(NatsConnection.java:733)
        at io.nats.client.impl.NatsConnection$2.run(NatsConnection.java:318)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space

**Comment by sasbury** [comment]
I will take a look. I ran the benchmarks with limited memory and  other memory tests but perhaps the  request/response or dispatcher has something I missed.

Thanks for the stack trace!

**Comment by locactus** [comment]
No probs! Please let me know if you need anything else.

**Comment by sasbury** [comment]
A few questions to get some context, since nothing jumped out at me:

* How many dispatchers are you running?
* What is the approximate subscription rate?
* How many connections are there?
* What is the approximate message rate?
* How long does it take to get to the OOM error?

**Comment by locactus** [comment]
- How many dispatchers are you running?
**I'm running 1 dispatcher in a JVM with one connection**

- What is the approximate subscription rate?
**Not sure how do I find this out?**

- How many connections are there?
**1**

- What is the approximate message rate?
**I'm taking in real time stock ticker information**

- Howlong does it take to get to the OOM error?
**I can get it to OOM error in 30 -45 min**

**Comment by sasbury** [comment]
thanks i will try to replicate

**Comment by locactus** [comment]
Cool, Just ran Visual VM to see if I could get anymore info and these seem to be the heavy hitters that just keep growing.  

Nats Connection Reader	2,105,311,200 B (41.7%)	5,357 B (0.5%)
Nats Connection Dispatcher	1,529,287,064 B (30.2%)	30,480 B (3%)

If you can't reproduce I think it maybe worth sharing my code and I'll get in touch with the ticker suppliers to see if I get get you a temp access token to test against their server. 
I'm on UK time so will check in tomorrow.

Thanks

**Comment by sasbury** [comment]
I am in meetings the rest of the week, so unless i get lucky this may have to wait until next week. But, maybe I get lucky.

**Comment by sasbury** [comment]
I created a test that I think matches your code (or approximates it.) can you take a look and let me know when you get a chance - 

https://gist.github.com/sasbury/b5c66cafb0d702974a4de688e929c37b

I ran the pub & sub for 1B+ messages and didn't have any issues. They both settled in to about 740mb and were very stable. I ran on 1 machine, if that matters.

The one "trick" i did is to make the publisher throttle to 1M/sec so that my machine didn't fly away.

If you want to try, you can alter that rate in the Ticker.java file at the top.

I am also curious if you can run these examples without the OOM. If you get an OOM can you let me know your OS versions and such.

**Comment by locactus** [comment]
Thanks for looking into this so quickly. 
I've made some amendments to your example and placed into a Spring Boot App 

[https://github.com/locactus/ostec-nats-jms-bridge-oom-test.git](url)

I think your test parameters are way above the level of stocks ticks I receive, so  a good test. Out of interest what server version are you running this against? I can go back to suppliers and check their version.  I'm running these tests against nats-server version 1.0.2. Actually think getting the supplier version is paramount as this test is void if they are running on a different version. 

Currently running test so will let you know if I get any OOM errors. 
Process running on windows box. Will see if I can run on Linux and check results
CPU  20% Memory 3,347MB Seems high, thinking this is the internal queue filling up while waiting to send messages via JMS.  Think I'm going to run without the messages going to JMS and just see that receiving the message and doing nothing with it.

**Comment by sasbury** [comment]
Sorry for delay, glad you worked it out. Let me know if you encounter any new problems.
