### ISSUE TITLE
The Jnats client bundle requires private-package from Eddsa while using in OSGi

### ISSUE THREAD

**Issue by oscerd** [nats-io/java-nats#199]
https://github.com/nats-io/java-nats/blob/f49af697311ddf37658641fe1fc07eadcfe4b611/build.gradle#L55

Trying to use the jnats client as feature dependency in camel-nats, I noticed that the nats-client requires private-package from eddsa, in particular from the math package

```
[org.ops4j.pax.exam.container.remote.RBCRemoteTarget] : Installed bundle (from stream) as ID: 86
[org.ops4j.pax.exam.container.remote.RBCRemoteTarget] : call [[TestAddress:PaxExam-b7a0e5b7-e3d3-439b-b49c-a9ee7442507f root:PaxExam-2edff29d-0f80-4582-8a23-d795e182156e]]
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=camel-nats; type=karaf.feature; version="[2.24.0.SNAPSHOT,2.24.0.SNAPSHOT]"; filter:="(&(osgi.identity=camel-nats)(type=karaf.feature)(version>=2.24.0.SNAPSHOT)(version<=2.24.0.SNAPSHOT))" [caused by: Unable to resolve camel-nats/2.24.0.SNAPSHOT: missing requirement [camel-nats/2.24.0.SNAPSHOT] osgi.identity; osgi.identity=org.apache.camel.camel-nats; type=osgi.bundle; version="[2.24.0.SNAPSHOT,2.24.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.apache.camel.camel-nats/2.24.0.SNAPSHOT: missing requirement [org.apache.camel.camel-nats/2.24.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=io.nats.client)(version>=2.3.0)(!(version>=3.0.0)))" [caused by: Unable to resolve io.nats.jnats/2.3.0: missing requirement [io.nats.jnats/2.3.0] osgi.wiring.package; filter:="(osgi.wiring.package=net.i2p.crypto.eddsa.math)"]]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:378)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:332)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:388)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1025)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:964)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve camel-nats/2.24.0.SNAPSHOT: missing requirement [camel-nats/2.24.0.SNAPSHOT] osgi.identity; osgi.identity=org.apache.camel.camel-nats; type=osgi.bundle; version="[2.24.0.SNAPSHOT,2.24.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.apache.camel.camel-nats/2.24.0.SNAPSHOT: missing requirement [org.apache.camel.camel-nats/2.24.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=io.nats.client)(version>=2.3.0)(!(version>=3.0.0)))" [caused by: Unable to resolve io.nats.jnats/2.3.0: missing requirement [io.nats.jnats/2.3.0] osgi.wiring.package; filter:="(osgi.wiring.package=net.i2p.crypto.eddsa.math)"]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.apache.camel.camel-nats/2.24.0.SNAPSHOT: missing requirement [org.apache.camel.camel-nats/2.24.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=io.nats.client)(version>=2.3.0)(!(version>=3.0.0)))" [caused by: Unable to resolve io.nats.jnats/2.3.0: missing requirement [io.nats.jnats/2.3.0] osgi.wiring.package; filter:="(osgi.wiring.package=net.i2p.crypto.eddsa.math)"]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 13 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve io.nats.jnats/2.3.0: missing requirement [io.nats.jnats/2.3.0] osgi.wiring.package; filter:="(osgi.wiring.package=net.i2p.crypto.eddsa.math)"
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 14 more
[org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer] : Shutting down the test container (Pax Runner)
```
This is because the eddsa bundle declares math package as private package here 
https://github.com/str4d/ed25519-java/blob/v0.3.0/pom.xml#L78

So I believe you need to do some manipulation in the client project, otherwise it won't work in an OSGi container.

**Comment by sasbury** [comment]
oscerd - i think i got this ripped out (i missed the public API for what we needed). Hoping to do a release today or tomorrow. Can you take a look and double check my work. If you see a problem and I release too fast I will do another one this week.

**Comment by oscerd** [comment]
Should be fine :-) I'll test the new release and provide you feedback asap. Thanks for the fast reaction!

**Comment by oscerd** [comment]
The Jnats bundle still requires math package from EDDSA

```
Import-Package: io.nats.client;version="[2.4,3)",io.nats.client.impl;v
 ersion="[2.4,3)",javax.net.ssl,net.i2p.crypto.eddsa,net.i2p.crypto.ed
 dsa.math,net.i2p.crypto.eddsa.spec
```

So it's still not working.

**Comment by sasbury** [comment]
Where is that coming from? I don't import math anywhere, or require it as far as I can tell. Even the pom doesn't have it (https://repo1.maven.org/maven2/io/nats/jnats/2.4.0/jnats-2.4.0.pom).

I need the eddsa package to implement nkeys, but I am not sure why it is reaching inside and getting the math package. Where do you see that import-package?

**Comment by oscerd** [comment]
In the manifest.mf of jnats jar. You need to tweak the maven bundle plugin config in your Pom I suppose

**Comment by sasbury** [comment]
ugh, i see it now, gradle is building that, i dont' see anywhere that I include it, i will dig more.

**Comment by sasbury** [comment]
ok, i may have "fixed" it. Can you try branch 2.4.1 and let me know if it works for you.

**Comment by oscerd** [comment]
Sure I will update you tomorrow.

**Comment by oscerd** [comment]
Thanks for your work and help

**Comment by oscerd** [comment]
I can confirm it works. The camel feature works fine and install itself on an OSGi container with 2.4.0-SNAPSHOT from v2.4.1 branch
