### ISSUE TITLE
Android API 26 error

### ISSUE THREAD

**Issue by Leondev7** [nats-io/java-nats#201]
I'm trying to write a test application in Android, currently I'm working with an API 26 device and every time I call the function Nats.connect() it throws this error.

` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.leondev7.natstest/com.example.leondev7.natstest.MainActivity}: java.io.IOException: Unable to connect to gnatsd server.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2861)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.io.IOException: Unable to connect to gnatsd server.
        at io.nats.client.impl.NatsConnection.connect(NatsConnection.java:185)
        at io.nats.client.impl.NatsImpl.createConnection(NatsImpl.java:28)
        at io.nats.client.Nats.createConnection(Nats.java:192)
        at io.nats.client.Nats.connect(Nats.java:98)
        at com.example.leondev7.natstest.MainActivity.onCreate(MainActivity.kt:15)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236)`

It doesn't matter if I set a server or don't, it always throws this error. 
I have java 8 compatibility in my gradle file and I'm using openjdk-8 to build the application

**Comment by sasbury** [comment]
what arguments are you passing in to connect?

**Comment by Leondev7** [comment]
I've tried with Nats.Connect("nats://nats.demo.io:4222") and Nats.Connect("nats.demo.io:4222")

**Comment by sasbury** [comment]
does the code work outside of android?

**Comment by Leondev7** [comment]
Yes, i've tried in my own machine and it works perfectly.

**Comment by sasbury** [comment]
Can you try this with the latest release? I am curious if this is still happening, and don't have a way to replicate.
