### ISSUE TITLE
[Exception] Filter is only supported when the queue is paused

### ISSUE THREAD

**Issue by dvasko** [nats-io/java-nats#203]
Exception
```
Fatal Exception: java.lang.IllegalStateException: Filter is only supported when the queue is paused
       at io.nats.client.impl.NatsConnectionWriter.io.nats.client.impl.MessageQueue.filter(NatsConnectionWriter.java:5278)
       at io.nats.client.impl.NatsConnection.closeSocketImpl(NatsConnection.java:565)
       at io.nats.client.impl.NatsConnection.closeSocket(NatsConnection.java:456)
       at io.nats.client.impl.NatsConnection.tryToConnect(NatsConnection.java:368)
       at io.nats.client.impl.NatsConnection.connect$1385ff(NatsConnection.java:171)
       at ourAppPackage.EventSocket.io.nats.client.impl.NatsImpl.createConnection(EventSocket.java)
```
is showing in really small number of sessions in our Android app

**Comment by sasbury** [comment]
I will take a look, hopefully it is an obvious thing, but sounds like a thread issue so if you notice any timing/context hints please let me know.

**Comment by sasbury** [comment]
That stack trace is out of date, so closing, but let me know if you see the issue again and i will try to find it. If you do see it and can create a sample to reproduce that would rock!

**Comment by dvasko** [comment]
Exception is still happening and it is a top crash in our Android app.
We can't reproduce the crash and we never experienced a crash in a dev environment.
Numbers that we see in production are let say 1000 crashes happened to ~1000 users.
It's evident that exception is happening in some edge cases probably related to threading/timing

**Comment by sasbury** [comment]
Are you getting a lot of disconnects, or are you open/closing regularly? I wonder if I can reproduce with a test that does a fast open/close over and over? Any ideas would be great. I have one thought I will try today.
