### ISSUE TITLE
exceptionOccurred gets called when closing a connection intentionally

### ISSUE THREAD

**Issue by yuanmwang-wf** [nats-io/java-nats#217]
Looks like when an error listener is passed to a connection, the error listener's `exceptionOccurred` method always gets called even when the connection is closed intentionally.  

Given the following example which implements a simple error listener, opens a connection and then closes the connection, I get the following output:
```java
[pool-1-thread-1] WARN examples.NatsPublisher - exception occurred
[pool-1-thread-1] ERROR examples.NatsPublisher - exception is
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at io.nats.client.impl.SocketDataPort.read(SocketDataPort.java:98)
	at io.nats.client.impl.NatsConnectionReader.run(NatsConnectionReader.java:114)
	at java.lang.Thread.run(Thread.java:748)
```

```java
public class NatsPublisher {

    private static final Logger LOGGER = LoggerFactory.getLogger(NatsPublisher.class);

    public static void main(String[] args) {
        ErrorListener errorListener = new ErrorListener() {
            @Override
            public void errorOccurred(io.nats.client.Connection connection, String s) {}

            @Override
            public void exceptionOccurred(io.nats.client.Connection connection, Exception e) {
                LOGGER.error("exceptionOccurred called", e);
            }

            @Override
            public void slowConsumerDetected(io.nats.client.Connection connection, Consumer consumer) {}
        };
        Options.Builder builder = new Options.Builder().server(Options.DEFAULT_URL).errorListener(errorListener);
        try {
            Connection conn = Nats.connect(builder.build());
            conn.close();
        } catch (Exception ignored) {}
    }
}
```

**Comment by sasbury** [comment]
I suspect we are over eager, i will take a look next time I am digging in to the library.
